language: node_js
sudo: true
dist: trusty
node_js:
  - 10
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install --pure-lockfile
script:
  - npm run dist
cache:
  directories:
  - "$HOME/.yarn-cache"
